[project]
name = "2025-26"
version = "0.1.0"
description = "PySpark course materials"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "findspark>=2.0.1",
    "notebook>=7.4.7",
    "pyspark>=3.5.0,<4.0.0",
    "pyarrow>=14.0.0"
]
